// Pre-built template library
// These are curated, high-quality templates ready for one-click installation

export interface TemplateMetadata {
    id: string;
    name: string;
    description: string;
    category: string;
    tags: string[];
    icon: string;
    isPro: boolean;
    price: number;
    author: string;
    downloads: number;
    rating: number;
    previewImage?: string; // URL or path to preview image
    duplicateLink?: string; // Notion duplicate URL for easy installation
}

export const TEMPLATE_CATEGORIES = [
    "All",
    "Productivity",
    "Finance",
    "Health & Fitness",
    "Content Creation",
    "Business",
    "Personal",
    "Education",
    "Travel",
    "Development",
    "Design",
    "Marketing"
] as const;

export const CURATED_TEMPLATES: TemplateMetadata[] = [
    // PRODUCTIVITY (20 templates)
    {
        id: "habit-tracker",
        name: "Habit Tracker",
        description: "Track your daily habits with streaks, analytics, and motivational insights. Perfect for building consistent routines.",
        category: "Productivity",
        tags: ["habits", "productivity", "self-improvement"],
        icon: "✅",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1247,
        rating: 4.9,
        previewImage: "/templates/habit-tracker.png"
    },
    {
        id: "project-tracker",
        name: "Project Tracker",
        description: "Manage multiple projects with tasks, timelines, and team collaboration. Includes Kanban and timeline views.",
        category: "Productivity",
        tags: ["projects", "tasks", "collaboration"],
        icon: "📊",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2156,
        rating: 4.8,
        previewImage: "/templates/project-tracker.png"
    },
    {
        id: "goal-tracker",
        name: "Goal Tracker",
        description: "Set and achieve your goals with milestones, progress tracking, and reflection prompts.",
        category: "Productivity",
        tags: ["goals", "productivity", "self-improvement"],
        icon: "🎯",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1834,
        rating: 4.9
    },
    {
        id: "daily-planner",
        name: "Daily Planner",
        description: "Plan your day with time blocks, priorities, and daily reflections. Includes weekly and monthly views.",
        category: "Productivity",
        tags: ["planning", "schedule", "time-management"],
        icon: "📅",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 3421,
        rating: 4.8
    },
    {
        id: "meeting-notes",
        name: "Meeting Notes Manager",
        description: "Organize meeting notes with action items, attendees, and follow-ups. Searchable and linkable.",
        category: "Productivity",
        tags: ["meetings", "notes", "collaboration"],
        icon: "📝",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2987,
        rating: 4.7
    },
    {
        id: "okr-tracker",
        name: "OKR Tracker",
        description: "Track Objectives and Key Results for teams and individuals. Quarterly reviews and progress dashboards.",
        category: "Productivity",
        tags: ["okr", "goals", "business"],
        icon: "🎯",
        isPro: true,
        price: 9,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.9
    },
    {
        id: "eisenhower-matrix",
        name: "Eisenhower Matrix",
        description: "Prioritize tasks using the urgent/important framework. Visual quadrant view for better decision-making.",
        category: "Productivity",
        tags: ["prioritization", "tasks", "productivity"],
        icon: "⚡",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1892,
        rating: 4.6
    },
    {
        id: "pomodoro-tracker",
        name: "Pomodoro Tracker",
        description: "Track your focus sessions with Pomodoro technique. Log completed sessions and analyze productivity patterns.",
        category: "Productivity",
        tags: ["focus", "time-management", "productivity"],
        icon: "🍅",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2134,
        rating: 4.7
    },
    {
        id: "weekly-review",
        name: "Weekly Review System",
        description: "Reflect on your week with wins, challenges, and next week's priorities. Includes gratitude journal.",
        category: "Productivity",
        tags: ["reflection", "planning", "journaling"],
        icon: "📖",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.8
    },
    {
        id: "reading-list",
        name: "Reading List & Book Tracker",
        description: "Track books you want to read, are reading, and have finished. Include notes, quotes, and ratings.",
        category: "Productivity",
        tags: ["reading", "books", "learning"],
        icon: "📚",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2456,
        rating: 4.9
    },
    {
        id: "note-taking-system",
        name: "Zettelkasten Note System",
        description: "Build a second brain with interconnected notes, tags, and backlinks. Perfect for researchers and writers.",
        category: "Productivity",
        tags: ["notes", "knowledge", "learning"],
        icon: "🧠",
        isPro: true,
        price: 12,
        author: "Bartlabs",
        downloads: 1234,
        rating: 4.9
    },
    {
        id: "decision-log",
        name: "Decision Log",
        description: "Document important decisions with context, alternatives considered, and outcomes. Learn from past choices.",
        category: "Productivity",
        tags: ["decisions", "documentation", "learning"],
        icon: "🤔",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 987,
        rating: 4.6
    },
    {
        id: "idea-inbox",
        name: "Idea Inbox",
        description: "Capture and organize ideas with tags, categories, and development stages. Never lose a great idea again.",
        category: "Productivity",
        tags: ["ideas", "creativity", "brainstorming"],
        icon: "💡",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.7
    },
    {
        id: "time-tracker",
        name: "Time Tracker",
        description: "Log time spent on projects and tasks. Generate reports and analyze where your time goes.",
        category: "Productivity",
        tags: ["time-tracking", "productivity", "analytics"],
        icon: "⏱️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2345,
        rating: 4.8
    },
    {
        id: "sprint-planner",
        name: "Sprint Planner",
        description: "Plan and execute 2-week sprints with backlog, sprint board, and retrospectives. Agile made simple.",
        category: "Productivity",
        tags: ["agile", "sprints", "project-management"],
        icon: "🏃",
        isPro: true,
        price: 15,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.9
    },
    {
        id: "kanban-board",
        name: "Kanban Board",
        description: "Visual workflow management with customizable columns. Track work in progress and completed tasks.",
        category: "Productivity",
        tags: ["kanban", "workflow", "tasks"],
        icon: "📋",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 3567,
        rating: 4.8
    },
    {
        id: "gtd-system",
        name: "Getting Things Done (GTD)",
        description: "Complete GTD implementation with inbox, next actions, projects, and contexts. Master productivity.",
        category: "Productivity",
        tags: ["gtd", "productivity", "organization"],
        icon: "✨",
        isPro: true,
        price: 18,
        author: "Bartlabs",
        downloads: 2134,
        rating: 4.9
    },
    {
        id: "wiki-knowledge-base",
        name: "Team Wiki & Knowledge Base",
        description: "Centralize team knowledge with docs, SOPs, and FAQs. Searchable and collaborative.",
        category: "Productivity",
        tags: ["wiki", "documentation", "knowledge"],
        icon: "📖",
        isPro: true,
        price: 20,
        author: "Bartlabs",
        downloads: 1789,
        rating: 4.8
    },
    {
        id: "bookmark-manager",
        name: "Bookmark Manager",
        description: "Save and organize web links with tags, categories, and notes. Your personal internet library.",
        category: "Productivity",
        tags: ["bookmarks", "links", "organization"],
        icon: "🔖",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.6
    },
    {
        id: "password-vault",
        name: "Password Vault",
        description: "Securely store passwords, API keys, and sensitive info. Organized by category with search.",
        category: "Productivity",
        tags: ["security", "passwords", "organization"],
        icon: "🔐",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2876,
        rating: 4.7
    },

    // FINANCE (15 templates)
    {
        id: "expense-tracker",
        name: "Expense Tracker",
        description: "Monitor your spending with categories, budgets, and visual analytics. Stay on top of your finances.",
        category: "Finance",
        tags: ["finance", "budget", "expenses"],
        icon: "💰",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 4123,
        rating: 4.9,
        previewImage: "/templates/expense-tracker.png"
    },
    {
        id: "budget-planner",
        name: "Budget Planner",
        description: "Create monthly budgets with income, expenses, and savings goals. Track actual vs planned spending.",
        category: "Finance",
        tags: ["budget", "finance", "planning"],
        icon: "💵",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 3456,
        rating: 4.8
    },
    {
        id: "investment-tracker",
        name: "Investment Portfolio Tracker",
        description: "Track stocks, crypto, and other investments. Monitor performance, dividends, and allocation.",
        category: "Finance",
        tags: ["investing", "stocks", "portfolio"],
        icon: "📈",
        isPro: true,
        price: 15,
        author: "Bartlabs",
        downloads: 2345,
        rating: 4.9
    },
    {
        id: "debt-payoff",
        name: "Debt Payoff Planner",
        description: "Track debts and create payoff strategies. Visualize progress with snowball or avalanche methods.",
        category: "Finance",
        tags: ["debt", "finance", "planning"],
        icon: "💳",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1987,
        rating: 4.7
    },
    {
        id: "subscription-tracker",
        name: "Subscription Tracker",
        description: "Monitor all your subscriptions with renewal dates and costs. Identify and cancel unused services.",
        category: "Finance",
        tags: ["subscriptions", "expenses", "tracking"],
        icon: "📱",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2678,
        rating: 4.8
    },
    {
        id: "invoice-manager",
        name: "Invoice Manager",
        description: "Create and track invoices for freelancers and small businesses. Monitor payment status and overdue amounts.",
        category: "Finance",
        tags: ["invoicing", "business", "finance"],
        icon: "🧾",
        isPro: true,
        price: 12,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.9
    },
    {
        id: "net-worth-tracker",
        name: "Net Worth Tracker",
        description: "Calculate and track your net worth over time. Include assets, liabilities, and growth charts.",
        category: "Finance",
        tags: ["net-worth", "finance", "wealth"],
        icon: "💎",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.8
    },
    {
        id: "savings-goals",
        name: "Savings Goals Tracker",
        description: "Set and track multiple savings goals. Visualize progress and calculate required monthly contributions.",
        category: "Finance",
        tags: ["savings", "goals", "finance"],
        icon: "🏦",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2234,
        rating: 4.7
    },
    {
        id: "tax-organizer",
        name: "Tax Organizer",
        description: "Organize tax documents, deductions, and receipts. Prepare for tax season stress-free.",
        category: "Finance",
        tags: ["taxes", "finance", "organization"],
        icon: "📊",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.6
    },
    {
        id: "crypto-portfolio",
        name: "Crypto Portfolio Tracker",
        description: "Track cryptocurrency holdings across wallets and exchanges. Monitor prices and portfolio value.",
        category: "Finance",
        tags: ["crypto", "investing", "portfolio"],
        icon: "₿",
        isPro: true,
        price: 10,
        author: "Bartlabs",
        downloads: 1987,
        rating: 4.8
    },
    {
        id: "rental-property",
        name: "Rental Property Manager",
        description: "Manage rental properties with tenant info, lease tracking, maintenance, and income/expenses.",
        category: "Finance",
        tags: ["real-estate", "rental", "property"],
        icon: "🏠",
        isPro: true,
        price: 18,
        author: "Bartlabs",
        downloads: 1234,
        rating: 4.9
    },
    {
        id: "business-finances",
        name: "Small Business Finances",
        description: "Track business income, expenses, invoices, and profit/loss. Simple bookkeeping for entrepreneurs.",
        category: "Finance",
        tags: ["business", "accounting", "finance"],
        icon: "💼",
        isPro: true,
        price: 25,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.9
    },
    {
        id: "bill-tracker",
        name: "Bill Payment Tracker",
        description: "Never miss a bill payment. Track due dates, amounts, and payment history with reminders.",
        category: "Finance",
        tags: ["bills", "payments", "finance"],
        icon: "📄",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2456,
        rating: 4.7
    },
    {
        id: "financial-dashboard",
        name: "Personal Finance Dashboard",
        description: "Complete financial overview with income, expenses, net worth, and goals in one place.",
        category: "Finance",
        tags: ["dashboard", "finance", "overview"],
        icon: "📊",
        isPro: true,
        price: 20,
        author: "Bartlabs",
        downloads: 2134,
        rating: 4.9
    },
    {
        id: "receipt-organizer",
        name: "Receipt Organizer",
        description: "Store and categorize receipts for expenses, warranties, and returns. Searchable database.",
        category: "Finance",
        tags: ["receipts", "expenses", "organization"],
        icon: "🧾",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1345,
        rating: 4.6
    },

    // HEALTH & FITNESS (12 templates)
    {
        id: "workout-tracker",
        name: "Workout Tracker",
        description: "Log your workouts, track progress, and plan your fitness journey with exercise databases and analytics.",
        category: "Health & Fitness",
        tags: ["fitness", "workout", "health"],
        icon: "💪",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2876,
        rating: 4.9
    },
    {
        id: "meal-planner",
        name: "Meal Planner",
        description: "Plan your weekly meals with recipes, shopping lists, and nutritional tracking.",
        category: "Health & Fitness",
        tags: ["food", "health", "planning"],
        icon: "🍽️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 3234,
        rating: 4.8
    },
    {
        id: "calorie-tracker",
        name: "Calorie & Macro Tracker",
        description: "Track daily calories, macros, and nutrition. Set goals and monitor progress towards targets.",
        category: "Health & Fitness",
        tags: ["nutrition", "diet", "health"],
        icon: "🥗",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2567,
        rating: 4.7
    },
    {
        id: "water-tracker",
        name: "Water Intake Tracker",
        description: "Track daily water consumption with goals and reminders. Build healthy hydration habits.",
        category: "Health & Fitness",
        tags: ["hydration", "health", "habits"],
        icon: "💧",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.6
    },
    {
        id: "sleep-tracker",
        name: "Sleep Tracker",
        description: "Log sleep hours, quality, and patterns. Identify factors affecting your sleep quality.",
        category: "Health & Fitness",
        tags: ["sleep", "health", "wellness"],
        icon: "😴",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2134,
        rating: 4.8
    },
    {
        id: "meditation-log",
        name: "Meditation & Mindfulness Log",
        description: "Track meditation sessions, techniques, and reflections. Build a consistent mindfulness practice.",
        category: "Health & Fitness",
        tags: ["meditation", "mindfulness", "wellness"],
        icon: "🧘",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.7
    },
    {
        id: "symptom-tracker",
        name: "Health Symptom Tracker",
        description: "Log symptoms, medications, and doctor visits. Share reports with healthcare providers.",
        category: "Health & Fitness",
        tags: ["health", "medical", "tracking"],
        icon: "🏥",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.8
    },
    {
        id: "running-log",
        name: "Running Log",
        description: "Track runs with distance, pace, routes, and personal records. Plan training for races.",
        category: "Health & Fitness",
        tags: ["running", "fitness", "training"],
        icon: "🏃",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1987,
        rating: 4.9
    },
    {
        id: "yoga-practice",
        name: "Yoga Practice Tracker",
        description: "Log yoga sessions, poses, and progress. Track flexibility and strength improvements.",
        category: "Health & Fitness",
        tags: ["yoga", "fitness", "wellness"],
        icon: "🧘‍♀️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.7
    },
    {
        id: "weight-tracker",
        name: "Weight & Body Measurements",
        description: "Track weight, body measurements, and progress photos. Visualize your fitness journey.",
        category: "Health & Fitness",
        tags: ["weight", "fitness", "tracking"],
        icon: "⚖️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2345,
        rating: 4.8
    },
    {
        id: "recipe-book",
        name: "Healthy Recipe Book",
        description: "Store healthy recipes with nutritional info, ingredients, and cooking instructions.",
        category: "Health & Fitness",
        tags: ["recipes", "cooking", "nutrition"],
        icon: "👨‍🍳",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2678,
        rating: 4.9
    },
    {
        id: "mental-health",
        name: "Mental Health Journal",
        description: "Track mood, emotions, and mental health patterns. Include gratitude and reflection prompts.",
        category: "Health & Fitness",
        tags: ["mental-health", "wellness", "journaling"],
        icon: "🌈",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.9
    },

    // CONTENT CREATION (10 templates)
    {
        id: "content-calendar",
        name: "Content Calendar",
        description: "Plan and schedule your content across platforms. Includes idea bank, publishing schedule, and analytics.",
        category: "Content Creation",
        tags: ["content", "social media", "marketing"],
        icon: "📅",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2987,
        rating: 4.9
    },
    {
        id: "youtube-planner",
        name: "YouTube Content Planner",
        description: "Plan videos with scripts, thumbnails, SEO, and publishing schedule. Track performance metrics.",
        category: "Content Creation",
        tags: ["youtube", "video", "content"],
        icon: "🎥",
        isPro: true,
        price: 15,
        author: "Bartlabs",
        downloads: 2134,
        rating: 4.9
    },
    {
        id: "blog-manager",
        name: "Blog Post Manager",
        description: "Manage blog posts from idea to publication. Track SEO keywords, drafts, and publishing dates.",
        category: "Content Creation",
        tags: ["blogging", "writing", "content"],
        icon: "✍️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.8
    },
    {
        id: "social-media-planner",
        name: "Social Media Planner",
        description: "Schedule posts across Instagram, Twitter, LinkedIn, and more. Content library and analytics.",
        category: "Content Creation",
        tags: ["social-media", "marketing", "content"],
        icon: "📱",
        isPro: true,
        price: 12,
        author: "Bartlabs",
        downloads: 2456,
        rating: 4.9
    },
    {
        id: "podcast-planner",
        name: "Podcast Production Hub",
        description: "Plan episodes, manage guests, track recording schedule, and organize show notes.",
        category: "Content Creation",
        tags: ["podcast", "audio", "content"],
        icon: "🎙️",
        isPro: true,
        price: 18,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.8
    },
    {
        id: "newsletter-manager",
        name: "Newsletter Manager",
        description: "Plan and organize email newsletters. Track topics, drafts, and subscriber engagement.",
        category: "Content Creation",
        tags: ["newsletter", "email", "content"],
        icon: "📧",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.7
    },
    {
        id: "video-production",
        name: "Video Production Tracker",
        description: "Manage video projects from pre-production to post. Track shots, edits, and deliverables.",
        category: "Content Creation",
        tags: ["video", "production", "filmmaking"],
        icon: "🎬",
        isPro: true,
        price: 20,
        author: "Bartlabs",
        downloads: 1234,
        rating: 4.9
    },
    {
        id: "photography-portfolio",
        name: "Photography Portfolio",
        description: "Organize photos by project, client, and category. Track editing status and deliverables.",
        category: "Content Creation",
        tags: ["photography", "portfolio", "creative"],
        icon: "📸",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1987,
        rating: 4.8
    },
    {
        id: "writing-projects",
        name: "Writing Projects Tracker",
        description: "Manage novels, articles, and writing projects. Track word count, deadlines, and submissions.",
        category: "Content Creation",
        tags: ["writing", "books", "creative"],
        icon: "📖",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.7
    },
    {
        id: "influencer-collab",
        name: "Influencer Collaboration Tracker",
        description: "Manage brand partnerships, sponsorships, and collaboration details. Track deliverables and payments.",
        category: "Content Creation",
        tags: ["influencer", "partnerships", "business"],
        icon: "🤝",
        isPro: true,
        price: 15,
        author: "Bartlabs",
        downloads: 1345,
        rating: 4.8
    },

    // BUSINESS (15 templates)
    {
        id: "crm-simple",
        name: "Simple CRM",
        description: "Manage client relationships with contacts, deals, and communication history. Perfect for freelancers and small businesses.",
        category: "Business",
        tags: ["crm", "clients", "sales"],
        icon: "👥",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 3456,
        rating: 4.9
    },
    {
        id: "sales-pipeline",
        name: "Sales Pipeline",
        description: "Track deals through your sales process. Forecast revenue and identify bottlenecks.",
        category: "Business",
        tags: ["sales", "pipeline", "crm"],
        icon: "💼",
        isPro: true,
        price: 20,
        author: "Bartlabs",
        downloads: 2134,
        rating: 4.9
    },
    {
        id: "client-portal",
        name: "Client Portal",
        description: "Share project updates, files, and invoices with clients. Professional client communication.",
        category: "Business",
        tags: ["clients", "portal", "communication"],
        icon: "🗂️",
        isPro: true,
        price: 25,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.8
    },
    {
        id: "freelance-business",
        name: "Freelance Business OS",
        description: "Complete freelance management: clients, projects, invoices, time tracking, and finances.",
        category: "Business",
        tags: ["freelance", "business", "management"],
        icon: "💻",
        isPro: true,
        price: 30,
        author: "Bartlabs",
        downloads: 2456,
        rating: 4.9
    },
    {
        id: "employee-directory",
        name: "Employee Directory",
        description: "Organize team information with contacts, roles, departments, and org charts.",
        category: "Business",
        tags: ["hr", "team", "organization"],
        icon: "👔",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.7
    },
    {
        id: "recruitment-pipeline",
        name: "Recruitment Pipeline",
        description: "Track candidates through hiring process. Schedule interviews and manage applications.",
        category: "Business",
        tags: ["hr", "recruitment", "hiring"],
        icon: "🎯",
        isPro: true,
        price: 18,
        author: "Bartlabs",
        downloads: 1345,
        rating: 4.8
    },
    {
        id: "vendor-management",
        name: "Vendor Management",
        description: "Track vendors, contracts, and purchase orders. Manage supplier relationships.",
        category: "Business",
        tags: ["vendors", "procurement", "business"],
        icon: "🏢",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 987,
        rating: 4.6
    },
    {
        id: "inventory-management",
        name: "Inventory Management",
        description: "Track stock levels, reorder points, and suppliers. Perfect for small retail businesses.",
        category: "Business",
        tags: ["inventory", "retail", "stock"],
        icon: "📦",
        isPro: true,
        price: 22,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.9
    },
    {
        id: "business-plan",
        name: "Business Plan Template",
        description: "Structure your business plan with market analysis, financials, and strategy sections.",
        category: "Business",
        tags: ["planning", "strategy", "startup"],
        icon: "📋",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1234,
        rating: 4.7
    },
    {
        id: "competitor-analysis",
        name: "Competitor Analysis",
        description: "Track competitors, their strategies, pricing, and market positioning. Stay ahead.",
        category: "Business",
        tags: ["competition", "market-research", "strategy"],
        icon: "🔍",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.8
    },
    {
        id: "product-roadmap",
        name: "Product Roadmap",
        description: "Plan product features, releases, and timelines. Align team on product vision.",
        category: "Business",
        tags: ["product", "roadmap", "planning"],
        icon: "🗺️",
        isPro: true,
        price: 15,
        author: "Bartlabs",
        downloads: 1987,
        rating: 4.9
    },
    {
        id: "customer-feedback",
        name: "Customer Feedback Hub",
        description: "Collect and organize customer feedback. Prioritize feature requests and bug reports.",
        category: "Business",
        tags: ["feedback", "customers", "product"],
        icon: "💬",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.7
    },
    {
        id: "swot-analysis",
        name: "SWOT Analysis",
        description: "Analyze strengths, weaknesses, opportunities, and threats for strategic planning.",
        category: "Business",
        tags: ["strategy", "analysis", "planning"],
        icon: "⚖️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1234,
        rating: 4.6
    },
    {
        id: "partnership-tracker",
        name: "Partnership Tracker",
        description: "Manage business partnerships, agreements, and collaboration opportunities.",
        category: "Business",
        tags: ["partnerships", "business", "collaboration"],
        icon: "🤝",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 876,
        rating: 4.7
    },
    {
        id: "business-metrics",
        name: "Business Metrics Dashboard",
        description: "Track KPIs, revenue, growth metrics, and business health indicators in one place.",
        category: "Business",
        tags: ["metrics", "kpi", "analytics"],
        icon: "📊",
        isPro: true,
        price: 20,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.9
    },

    // PERSONAL (8 templates)
    {
        id: "life-dashboard",
        name: "Life Dashboard",
        description: "Central hub for all areas of life: goals, habits, finances, health, and relationships.",
        category: "Personal",
        tags: ["dashboard", "life", "organization"],
        icon: "🌟",
        isPro: true,
        price: 25,
        author: "Bartlabs",
        downloads: 2345,
        rating: 4.9
    },
    {
        id: "gratitude-journal",
        name: "Gratitude Journal",
        description: "Daily gratitude practice with prompts and reflections. Build positivity and mindfulness.",
        category: "Personal",
        tags: ["gratitude", "journaling", "wellness"],
        icon: "🙏",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.8
    },
    {
        id: "bucket-list",
        name: "Bucket List",
        description: "Track life goals and experiences you want to have. Check off completed dreams.",
        category: "Personal",
        tags: ["goals", "life", "experiences"],
        icon: "🪣",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.7
    },
    {
        id: "relationship-tracker",
        name: "Relationship Tracker",
        description: "Nurture relationships with contact logs, gift ideas, and important dates.",
        category: "Personal",
        tags: ["relationships", "contacts", "social"],
        icon: "❤️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1234,
        rating: 4.6
    },
    {
        id: "home-inventory",
        name: "Home Inventory",
        description: "Catalog belongings for insurance, moving, or organization. Include photos and values.",
        category: "Personal",
        tags: ["home", "inventory", "organization"],
        icon: "🏠",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 987,
        rating: 4.5
    },
    {
        id: "car-maintenance",
        name: "Car Maintenance Log",
        description: "Track vehicle maintenance, repairs, and expenses. Never miss an oil change.",
        category: "Personal",
        tags: ["car", "maintenance", "tracking"],
        icon: "🚗",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.7
    },
    {
        id: "pet-care",
        name: "Pet Care Tracker",
        description: "Track vet visits, medications, feeding schedules, and pet expenses.",
        category: "Personal",
        tags: ["pets", "care", "tracking"],
        icon: "🐾",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.8
    },
    {
        id: "gift-planner",
        name: "Gift Planner",
        description: "Track gift ideas, purchases, and occasions. Never forget a birthday or anniversary.",
        category: "Personal",
        tags: ["gifts", "planning", "occasions"],
        icon: "🎁",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1345,
        rating: 4.6
    },

    // EDUCATION (8 templates)
    {
        id: "student-dashboard",
        name: "Student Dashboard",
        description: "All-in-one student workspace with assignments, notes, grades, and study schedules.",
        category: "Education",
        tags: ["student", "education", "study"],
        icon: "🎓",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 4567,
        rating: 4.9
    },
    {
        id: "course-planner",
        name: "Course Planner",
        description: "Plan and organize courses with syllabus, assignments, and exam schedules.",
        category: "Education",
        tags: ["courses", "planning", "education"],
        icon: "📚",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2345,
        rating: 4.8
    },
    {
        id: "research-tracker",
        name: "Research Project Tracker",
        description: "Organize research with sources, notes, citations, and writing progress.",
        category: "Education",
        tags: ["research", "academic", "writing"],
        icon: "🔬",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.7
    },
    {
        id: "flashcard-system",
        name: "Flashcard Study System",
        description: "Create and organize flashcards for spaced repetition learning. Track mastery levels.",
        category: "Education",
        tags: ["study", "flashcards", "learning"],
        icon: "🗂️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2134,
        rating: 4.9
    },
    {
        id: "language-learning",
        name: "Language Learning Tracker",
        description: "Track vocabulary, grammar, practice sessions, and language learning progress.",
        category: "Education",
        tags: ["language", "learning", "study"],
        icon: "🌍",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.8
    },
    {
        id: "teacher-planner",
        name: "Teacher Planner",
        description: "Plan lessons, track student progress, and manage classroom activities.",
        category: "Education",
        tags: ["teaching", "education", "planning"],
        icon: "👨‍🏫",
        isPro: true,
        price: 15,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.9
    },
    {
        id: "online-course-tracker",
        name: "Online Course Tracker",
        description: "Track online courses from Udemy, Coursera, etc. Monitor progress and certificates.",
        category: "Education",
        tags: ["courses", "online-learning", "education"],
        icon: "💻",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1987,
        rating: 4.7
    },
    {
        id: "study-schedule",
        name: "Study Schedule Planner",
        description: "Create study schedules with time blocks, subjects, and break reminders.",
        category: "Education",
        tags: ["study", "schedule", "planning"],
        icon: "📅",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2234,
        rating: 4.8
    },

    // TRAVEL (6 templates)
    {
        id: "travel-planner",
        name: "Travel Planner",
        description: "Plan your trips with itineraries, bookings, packing lists, and budget tracking.",
        category: "Travel",
        tags: ["travel", "vacation", "planning"],
        icon: "✈️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2987,
        rating: 4.9
    },
    {
        id: "trip-itinerary",
        name: "Trip Itinerary Builder",
        description: "Create detailed day-by-day itineraries with activities, reservations, and maps.",
        category: "Travel",
        tags: ["itinerary", "travel", "planning"],
        icon: "🗺️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.8
    },
    {
        id: "packing-list",
        name: "Packing List Generator",
        description: "Create customizable packing lists for different trip types. Never forget essentials.",
        category: "Travel",
        tags: ["packing", "travel", "checklist"],
        icon: "🎒",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2134,
        rating: 4.7
    },
    {
        id: "travel-journal",
        name: "Travel Journal",
        description: "Document your travels with photos, memories, and reflections from each destination.",
        category: "Travel",
        tags: ["journal", "travel", "memories"],
        icon: "📖",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.9
    },
    {
        id: "destination-research",
        name: "Destination Research Hub",
        description: "Research destinations with attractions, restaurants, hotels, and travel tips.",
        category: "Travel",
        tags: ["research", "travel", "planning"],
        icon: "🌎",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1345,
        rating: 4.6
    },
    {
        id: "travel-budget",
        name: "Travel Budget Tracker",
        description: "Track trip expenses by category. Stay within budget while traveling.",
        category: "Travel",
        tags: ["budget", "travel", "expenses"],
        icon: "💰",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.8
    },

    // DEVELOPMENT (6 templates)
    {
        id: "bug-tracker",
        name: "Bug Tracker",
        description: "Track bugs, issues, and technical debt. Prioritize and assign to team members.",
        category: "Development",
        tags: ["bugs", "development", "tracking"],
        icon: "🐛",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2456,
        rating: 4.9
    },
    {
        id: "code-snippets",
        name: "Code Snippets Library",
        description: "Save and organize code snippets with syntax highlighting and tags.",
        category: "Development",
        tags: ["code", "snippets", "development"],
        icon: "💻",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 2134,
        rating: 4.8
    },
    {
        id: "api-documentation",
        name: "API Documentation",
        description: "Document APIs with endpoints, parameters, examples, and authentication details.",
        category: "Development",
        tags: ["api", "documentation", "development"],
        icon: "📡",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.7
    },
    {
        id: "tech-stack",
        name: "Tech Stack Tracker",
        description: "Document technologies, tools, and frameworks used in projects.",
        category: "Development",
        tags: ["tech-stack", "development", "documentation"],
        icon: "🛠️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.6
    },
    {
        id: "learning-roadmap",
        name: "Developer Learning Roadmap",
        description: "Plan your learning path with technologies to learn, resources, and progress tracking.",
        category: "Development",
        tags: ["learning", "development", "roadmap"],
        icon: "🗺️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1987,
        rating: 4.9
    },
    {
        id: "deployment-checklist",
        name: "Deployment Checklist",
        description: "Ensure smooth deployments with pre-launch checklists and rollback procedures.",
        category: "Development",
        tags: ["deployment", "devops", "checklist"],
        icon: "🚀",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.8
    },

    // DESIGN (4 templates)
    {
        id: "design-system",
        name: "Design System",
        description: "Document design tokens, components, and guidelines for consistent UI/UX.",
        category: "Design",
        tags: ["design-system", "ui", "documentation"],
        icon: "🎨",
        isPro: true,
        price: 20,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.9
    },
    {
        id: "client-projects",
        name: "Design Client Projects",
        description: "Manage design projects with briefs, revisions, feedback, and deliverables.",
        category: "Design",
        tags: ["design", "clients", "projects"],
        icon: "🖌️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.8
    },
    {
        id: "brand-guidelines",
        name: "Brand Guidelines",
        description: "Document brand identity with logos, colors, typography, and usage guidelines.",
        category: "Design",
        tags: ["branding", "design", "guidelines"],
        icon: "🏷️",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1234,
        rating: 4.7
    },
    {
        id: "inspiration-board",
        name: "Design Inspiration Board",
        description: "Collect and organize design inspiration with images, links, and notes.",
        category: "Design",
        tags: ["inspiration", "design", "creativity"],
        icon: "✨",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1876,
        rating: 4.8
    },

    // MARKETING (6 templates)
    {
        id: "marketing-campaigns",
        name: "Marketing Campaign Tracker",
        description: "Plan and track marketing campaigns with goals, budgets, and performance metrics.",
        category: "Marketing",
        tags: ["marketing", "campaigns", "analytics"],
        icon: "📢",
        isPro: true,
        price: 18,
        author: "Bartlabs",
        downloads: 1987,
        rating: 4.9
    },
    {
        id: "email-marketing",
        name: "Email Marketing Planner",
        description: "Plan email campaigns with sequences, templates, and performance tracking.",
        category: "Marketing",
        tags: ["email", "marketing", "campaigns"],
        icon: "📧",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1678,
        rating: 4.8
    },
    {
        id: "seo-tracker",
        name: "SEO Tracker",
        description: "Track keywords, rankings, backlinks, and SEO performance for your website.",
        category: "Marketing",
        tags: ["seo", "marketing", "analytics"],
        icon: "🔍",
        isPro: true,
        price: 15,
        author: "Bartlabs",
        downloads: 1567,
        rating: 4.9
    },
    {
        id: "lead-magnet-tracker",
        name: "Lead Magnet Tracker",
        description: "Track lead magnets, opt-in rates, and conversion funnels.",
        category: "Marketing",
        tags: ["leads", "marketing", "conversion"],
        icon: "🧲",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1345,
        rating: 4.7
    },
    {
        id: "brand-mentions",
        name: "Brand Mentions Tracker",
        description: "Monitor brand mentions, reviews, and social media sentiment.",
        category: "Marketing",
        tags: ["brand", "monitoring", "social-media"],
        icon: "👀",
        isPro: false,
        price: 0,
        author: "Bartlabs",
        downloads: 1234,
        rating: 4.6
    },
    {
        id: "affiliate-program",
        name: "Affiliate Program Manager",
        description: "Manage affiliates, track commissions, and monitor referral performance.",
        category: "Marketing",
        tags: ["affiliate", "marketing", "tracking"],
        icon: "🤝",
        isPro: true,
        price: 20,
        author: "Bartlabs",
        downloads: 1456,
        rating: 4.8
    }
];
